### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by shifuma** [billmn/craft-turnstile#2]
Hi there! Now that Craft 5.0 is out, I wanted to see if you had plans to upgrade this plugin?

**Comment by billmn** [comment]
Yes, I plan to release a new version later today.

**Comment by shifuma** [comment]
Amazing, thank you (and sorry, I wasn't meaning to be impatient!)

**Comment by billmn** [comment]
v2 has been released with Craft 5 compatibility.
