### ISSUE TITLE
Verify Turnstile for public registrations

### ISSUE THREAD

**Issue by martijnckx** [billmn/craft-turnstile#3]
My project receives a lot of spam registrations at the moment, because there is no Turnstile verification on public registration. Would you be interested in adding this to the plugin? `c10d-dev/craft-recaptcha` implemented it like this: https://github.com/c10d-dev/craft-recaptcha/blob/38953ed8adf9a9ee06e647424b9ae8e5c93a9b75/src/CraftRecaptcha.php#L145

**Comment by billmn** [comment]
@martijnckx What version of Craft CMS are you using in your project?

I am considering whether or not to implement this feature for v1 of the plugin as well.

**Comment by martijnckx** [comment]
@billmn I'm using Craft Pro 4.9.7, and my fork has been working perfectly for me since last week.

**Comment by billmn** [comment]
@martijnckx I have just released v1.0.4 for Craft 4.

I will also release an update for v2 for Craft 5 shortly.

Thank you!
